### ISSUE TITLE
Bug: Global notification email in Admin are not recognized as toEmail in aws(ses), but as fromEmail.

### ISSUE THREAD

**Issue by zahmis** [weseek/growi#3524] opened 2021-03-12 08:19 UTC
Environment
------------

### Host

| item     | version |
| ---      | --- |
|GROWI     |4.2.13-RC|

How to reproduce? (再現手順)
---------------------------

1. Create identiy of ses  
1. Create an IAM with ses privileges.  
1. Go to App Settings in admin.  
  Input Mail Setting in Admin, and select ses.  
  Enter the from address as verified by ses.  
  Enter the Access Key ID and Secret access key as obtained by  created IAM.
<img width="903" alt="スクリーンショット 2021-03-12 17 05 11" src="https://user-images.githubusercontent.com/57100766/110910843-38014c00-8355-11eb-8b50-4e27d3c92a3e.png">  
 Press the Update button  

4.   Go to Notification Settings.  
  Click Global notification.
  Click add new
  Enter the required information
<img width="1389" alt="スクリーンショット 2021-03-12 17 05 38" src="https://user-images.githubusercontent.com/57100766/110910878-45b6d180-8355-11eb-9e86-98960136942b.png">

  Enter the required information  

What happens? (症状)
---------------------
- The following error occurs on the server side.

```
POST /_api/pages.update 200 78.062 ms - 1512
08:03:05.972Z  INFO growi:service:search-delegator:elasticsearch: Adding pages progressing: (count=1, errors=false, took=504ms)
08:03:05.972Z  INFO growi:service:search-delegator:elasticsearch: Adding pages has completed: (totalCount=1, skipped=0)
08:03:06.244Z ERROR growi:routes:page:
  Edit notification failed MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-1: trigger@applet.ifttt.com
      at Request.extractError (/workspace/growi/node_modules/aws-sdk/lib/protocol/query.js:47:29)
      at Request.callListeners (/workspace/growi/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
      at Request.emit (/workspace/growi/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (/workspace/growi/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/workspace/growi/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/workspace/growi/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /workspace/growi/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/workspace/growi/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/workspace/growi/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/workspace/growi/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at Request.emit (/workspace/growi/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (/workspace/growi/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/workspace/growi/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/workspace/growi/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /workspace/growi/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/workspace/growi/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/workspace/growi/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/workspace/growi/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at callNextListener (/workspace/growi/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
      at IncomingMessage.onEnd (/workspace/growi/node_modules/aws-sdk/lib/event_listeners.js:269:13)
      at IncomingMessage.emit (events.js:327:22)
      at IncomingMessage.EventEmitter.emit (domain.js:467:12) {
    code: 'MessageRejected',
    time: 2021-03-12T08:03:06.240Z,
    requestId: '4ce30473-9123-4ea3-908b-7120b26690e9',
    statusCode: 400,
    retryable: false,
    retryDelay: 87.61044496853141
  }
```

What is the expected result? (期待される動作)
-------------------------------------------
-　An email will be sent when the trigger is activated. 

Note
- This error does not happen using smtp server.
- No problem if you use aws(ses) to send user invites.

**Comment by kaoritokashiki** [comment] 2022-06-09 04:57
Thanks for reporting the issue.

```
 Email address is not verified. The following identities failed the check in region US-EAST-1: hoge@example.com
```

The error you mentioned will be occured in case that SES settings is Sandbox mode.
Please check the following link to solve the error.
https://docs.aws.amazon.com/ses/latest/dg/request-production-access.html

For the above reason, this is not a bug of GROWI, I'll close this issue.

Thank you.

**Closed by kaoritokashiki** 2022-06-09 04:57 UTC
Labels: looking for implementers, bug, under investigation, priority minor
