### ISSUE TITLE
Imprv: Enable to download an attached file with original name(添付ファイルを元の名前でダウンロードできるようにしてほしい)

### ISSUE THREAD

**Issue by tshimokawa** [weseek/growi#287] opened 2018-03-02 01:27 UTC
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | windows 2016 |
|crowi-plus|2.4.0-RC|
|node.js   |6.11.5|
|npm       |3.10.10|
|Using Docker|no|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        | windows 7|
|browser   | chrome |

How to reproduce? (再現手順)
---------------------------

- download an attached file by clicking link
(添付ファイルのリンクをクリックしてダウンロードする)

What happens? (症状)
---------------------

- the file is downloaded with a name which is "ObjectID" + "original file Extension"
(ファイル名がオブジェクトID＋元の拡張子でダウンロードされる)

What is the expected result? (期待される動作)
-------------------------------------------

- the file is downloaded with an original name
(アップロード時の元のファイル名でダウンロードできるようにしてほしい)

**Comment by dev-hayash** [comment] 2018-03-14 08:10
I misstake posted the same issue on crowi's github.
[https://github.com/crowi/crowi/issues/262](https://github.com/crowi/crowi/issues/262)

Modified sources are also merged with crowi-plus, but since crowi and crowi-plus have different upload paths, the problem is not solved.

**Comment by kwsk8910** [comment] 2018-03-15 10:06
@tshimokawa 
I was able to reproduce the problem. I investigate the cause of the problem from now on.

@dev-hayash 
Thank you for reporting! I make use of it for a solution to the problem.

**Closed** 2018-04-16 07:10 UTC
Labels: user requests

**Comment by yuki-takei** [comment] 2018-04-16 07:12
@tshimokawa @dev-hayash 
I am sorry to have kept you waiting.
Next v3.0.7 release solve this problem.
