### ISSUE TITLE
Improvement: Can't recover pages published to the deleted group

### ISSUE THREAD

**Issue by cignoir** [weseek/growi#826] opened 2019-02-06 01:53 UTC
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Amazon Linux 2|
|GROWI     |3.3.6|
|node.js   |8.15.0|
|npm       |6.4.1|
|Using Docker|no|
|Using [growi-docker-compose][growi-docker-compose]|no|

### Client

| item     | version |
| ---      | --- |
|OS        |Windows10 Professional 64bit|
|browser   |Chrome 71.0.3578.98|

How to reproduce? (再現手順)
---------------------------

1. Create `Group A`
2. Publish a page to `Group A` only.
3. Delete `Group A`

What happens? (症状)
---------------------

* There is no way to recover pages published to the deleted group.

What is the expected result? (期待される動作)
-------------------------------------------

* Prevent deleting `Group A` If there are pages or users belonging to the group.
or
* Grant admin the authority to access all pages.

**Comment by yuki-takei** [comment] 2019-02-12 11:36
@cignoir Thank you for your report.

Although the current version of GROWI reproduces it, the behavior is not considered well in fact.

We should fix it but the priority will be low because I think all of pages which belong to Group1 will be unnecessary if the Group1 is removed.
What do you think?

**Comment by cignoir** [comment] 2019-02-14 11:11
@yuki-takei  Thank you for consideration!

I agree the priority is low as you say.

I think the problem is that users can't imagine what happens when deleting a group with pages associated with it. Someone may think there is no problem because it is an unnecessary page. But someone else may think the page just becomes public. It may cause operational errors easily.

**Comment by yuki-takei** [comment] 2019-05-17 09:36
This feature will be released on v3.4.7.

**Closed** 2019-05-17 09:35 UTC
Labels: user requests
