### ISSUE TITLE
Bug: Sign in Failure when using Google OAuth(Passport)

### ISSUE THREAD

**Issue by h-ohta** [weseek/growi#787] opened 2019-01-09 05:15 UTC
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | Ubuntu 18.04.1 on Microsoft Azure |
|GROWI     | 3.3.3 |
|node.js   | 8.14.1 |
|npm       | 6.4.1 |
|Using Docker| yes |
|Using [growi-docker-compose][growi-docker-compose]| yes |

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        | macOS Mojave 10.14.2 |
|browser   | Vivaldi 2.2.1388.37 |

How to reproduce? (再現手順)
---------------------------

1. Set some parameters at Google OAuth settings by following `Google OAuth の設定方法`
1. Click `ログイン by Google Account` at `/login`
1. Select an account which you want to use for Growi and go back to `/login`

What happens? (症状)
---------------------

- Sign in Failure

```
nginx_1          | 222.159.129.16 - - [09/Jan/2019:05:07:28 +0000] "GET /passport/google? HTTP/1.1" 302 0 "https://xxx.xxx.jp/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Viv/2.2.1388.37"
app_1            | [2019-01-09T05:07:28.553Z]  INFO: express/74 on 01fa1a2fa846: ::ffff:172.18.0.5 <-- GET /passport/google? HTTP/1.0 302 0 https://xxx.xxx.jp/login Chrome 71.0 Mac OS X 10.14.2 1.35879 ms (req_id=3954213d-d5ef-45ac-b5b4-7ae7199749ad)
app_1            | [2019-01-09T05:07:32.073Z] DEBUG: growi:routes:login-passport/74 on 01fa1a2fa846: --- authenticate with google strategy ---
app_1            | [2019-01-09T05:07:32.073Z] DEBUG: growi:routes:login-passport/74 on 01fa1a2fa846:
app_1            |   response { kind: 'plus#person',
app_1            |     etag: '"jb1Xzanox6i8Zyse4DcYD8sZqy0/5tvti_G5UlRPsssVCdkUn5lp01U"',
app_1            |     emails: [ { value: 'zzz.yyy@xxx.jp', type: 'account' } ],
app_1            |     objectType: 'person',
app_1            |     id: '100129916388694118237',
app_1            |     displayName: 'zzz yyy',
app_1            |     name: { familyName: 'yyy', givenName: 'zzz' },
app_1            |     image: 
app_1            |      { url: 'https://lh5.googleusercontent.com/-3tnvghhzJgc/AAAAAAAAAAI/AAAAAAAAAAA/AKxrwcaOokYaUnKfW4dvxfaBX7c5DGo9BQ/mo/photo.jpg?sz=50',
app_1            |        isDefault: true },
app_1            |     isPlusUser: false,
app_1            |     language: 'ja',
app_1            |     verified: false,
app_1            |     domain: 'xxx.jp',
app_1            |     provider: 'google' }
app_1            | [2019-01-09T05:07:32.073Z] DEBUG: growi:routes:login-passport/74 on 01fa1a2fa846: info undefined
app_1            | [2019-01-09T05:07:32.077Z] DEBUG: growi:models:external-account/74 on 01fa1a2fa846: ExternalAccount '100129916388694118237' is not found, it is going to be registered.
app_1            | [2019-01-09T05:07:32.080Z] DEBUG: growi:models:user/74 on 01fa1a2fa846:
app_1            |   createUserByEmailAndPassword failed:  { ValidationError: User validation failed: lang: `` is not a valid enum value for path `lang`.
app_1            |       at ValidationError.inspect (/opt/growi/node_modules/mongoose/lib/error/validation.js:59:24)
app_1            |       at formatValue (util.js:399:38)
app_1            |       at inspect (util.js:293:10)
app_1            |       at Logger.format (util.js:222:18)
app_1            |       at mkRecord (/opt/growi/node_modules/bunyan/lib/bunyan.js:984:22)
app_1            |       at Logger.debug (/opt/growi/node_modules/bunyan/lib/bunyan.js:1044:19)
app_1            |       at /opt/growi/src/server/models/user.js:770:9
app_1            |       at /opt/growi/node_modules/mongoose/lib/model.js:4487:16
app_1            |       at $__save.error (/opt/growi/node_modules/mongoose/lib/model.js:402:16)
app_1            |       at /opt/growi/node_modules/kareem/index.js:246:48
app_1            |       at next (/opt/growi/node_modules/kareem/index.js:167:27)
nginx_1          | 222.159.129.16 - - [09/Jan/2019:05:07:32 +0000] "GET /passport/google/callback?code=4/zQC7FsdVo5eILPRGVrqEZluRREQ3MdJmf33KPV9S90hZb0WM_IpcdO7j0jCu9cpvlWkGzEHy24CSTCIQikkeFIc&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email HTTP/1.1" 302 56 "https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=1034953606325-st8o19khq8jvpvqoaiu76m5feh0hsnmr.apps.googleusercontent.com&as=FX2iw3LSwJd2JRtN6ytXXw&destination=https%3A%2F%2Fxxx.xxx.jp&approval_state=!ChR3UXllM3BNb0twYlZEZkdtcW5uTxIfNDdJaW00eFF0TFlTNEJxcmlYbTVkb2xTenlFUWd4WQ%E2%88%99APNbktkAAAAAXDbTENwbKQxJdXvlCbqs5VzqAmiyUyDW&oauthgdpr=1&xsrfsig=ChkAeAh8TzBrvC0eUG5xu4FTE4mtSBZcfOK_Eg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Viv/2.2.1388.37"
app_1            |       at next (/opt/growi/node_modules/kareem/index.js:169:9)
app_1            |       at Kareem.execPost (/opt/growi/node_modules/kareem/index.js:217:3)
app_1            |       at _handleWrapError (/opt/growi/node_modules/kareem/index.js:245:21)
app_1            |       at /opt/growi/node_modules/kareem/index.js:272:14
app_1            |       at _next (/opt/growi/node_modules/kareem/index.js:94:14)
app_1            |       at process.nextTick (/opt/growi/node_modules/kareem/index.js:499:38)
app_1            |       at _combinedTickCallback (internal/process/next_tick.js:132:7)
app_1            |       at process._tickDomainCallback (internal/process/next_tick.js:219:9)
app_1            |     errors: 
app_1            |      { lang: 
app_1            |         { ValidatorError: `` is not a valid enum value for path `lang`.
app_1            |       at new ValidatorError (/opt/growi/node_modules/mongoose/lib/error/validator.js:29:11)
app_1            |       at validate (/opt/growi/node_modules/mongoose/lib/schematype.js:838:13)
app_1            |       at /opt/growi/node_modules/mongoose/lib/schematype.js:887:11
app_1            |       at Array.forEach (<anonymous>)
app_1            |       at SchemaString.SchemaType.doValidate (/opt/growi/node_modules/mongoose/lib/schematype.js:847:19)
app_1            |       at /opt/growi/node_modules/mongoose/lib/document.js:1838:9
app_1            |       at _combinedTickCallback (internal/process/next_tick.js:132:7)
app_1            |       at process._tickDomainCallback (internal/process/next_tick.js:219:9)
app_1            |           message: '`` is not a valid enum value for path `lang`.',
app_1            |           name: 'ValidatorError',
app_1            |           properties: [Object],
app_1            |           kind: 'enum',
app_1            |           path: 'lang',
app_1            |           value: '',
app_1            |           reason: undefined,
app_1            |           '$isValidatorError': true } },
app_1            |     _message: 'User validation failed',
app_1            |     name: 'ValidationError' }
app_1            | [2019-01-09T05:07:32.084Z]  INFO: express/74 on 01fa1a2fa846: ::ffff:172.18.0.5 <-- GET /passport/google/callback?code=4/zQC7FsdVo5eILPRGVrqEZluRREQ3MdJmf33KPV9S90hZb0WM_IpcdO7j0jCu9cpvlWkGzEHy24CSTCIQikkeFIc&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email HTTP/1.0 302 56 https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=1034953606325-st8o19khq8jvpvqoaiu76m5feh0hsnmr.apps.googleusercontent.com&as=FX2iw3LSwJd2JRtN6ytXXw&destination=https%3A%2F%2Fxxx.xxx.jp&approval_state=!ChR3UXllM3BNb0twYlZEZkdtcW5uTxIfNDdJaW00eFF0TFlTNEJxcmlYbTVkb2xTenlFUWd4WQ%E2%88%99APNbktkAAAAAXDbTENwbKQxJdXvlCbqs5VzqAmiyUyDW&oauthgdpr=1&xsrfsig=ChkAeAh8TzBrvC0eUG5xu4FTE4mtSBZcfOK_Eg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow Chrome 71.0 Mac OS X 10.14.2 405.25515 ms (req_id=2ccb4700-9308-473b-8ea6-ffb06c60c103)
nginx_1          | 222.159.129.16 - - [09/Jan/2019:05:07:32 +0000] "GET /login HTTP/1.1" 200 15580 "https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=1034953606325-st8o19khq8jvpvqoaiu76m5feh0hsnmr.apps.googleusercontent.com&as=FX2iw3LSwJd2JRtN6ytXXw&destination=https%3A%2F%2Fxxx.xxx.jp&approval_state=!ChR3UXllM3BNb0twYlZEZkdtcW5uTxIfNDdJaW00eFF0TFlTNEJxcmlYbTVkb2xTenlFUWd4WQ%E2%88%99APNbktkAAAAAXDbTENwbKQxJdXvlCbqs5VzqAmiyUyDW&oauthgdpr=1&xsrfsig=ChkAeAh8TzBrvC0eUG5xu4FTE4mtSBZcfOK_Eg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37"
app_1            | [2019-01-09T05:07:32.115Z]  INFO: express/74 on 01fa1a2fa846: ::ffff:172.18.0.5 <-- GET /login HTTP/1.0 200 15580 https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=1034953606325-st8o19khq8jvpvqoaiu76m5feh0hsnmr.apps.googleusercontent.com&as=FX2iw3LSwJd2JRtN6ytXXw&destination=https%3A%2F%2Fxxx.xxx.jp&approval_state=!ChR3UXllM3BNb0twYlZEZkdtcW5uTxIfNDdJaW00eFF0TFlTNEJxcmlYbTVkb2xTenlFUWd4WQ%E2%88%99APNbktkAAAAAXDbTENwbKQxJdXvlCbqs5VzqAmiyUyDW&oauthgdpr=1&xsrfsig=ChkAeAh8TzBrvC0eUG5xu4FTE4mtSBZcfOK_Eg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow Vivaldi 2.2 Mac OS X 10.14.2 3.092177 ms (req_id=98f8ef90-5caa-4aa1-bf42-cd8c564595c0)
```

What is the expected result? (期待される動作)
-------------------------------------------

- Sign in success

Note
----

To get Stacktrace, I set the following Environment Variables at `docker-compose.yml`.

```
DEBUG=growi:crowi,growi:routes:login-passport,growi:service:PassportService,growi:models:external-account,growi:models:user
```

**Comment by yuki-takei** [comment] 2019-01-10 13:42
@h-ohta Thank you for your report.

It seems to an bug and I tried to reproduce that, but it didn't.

The most wondering thing is 'lang' is set as an empty string, but I don't no idea about when the value was set and where it came from.

Anyway, would you try the following workaround and report again to me?

1. Go to `/admin/app`
1. Modify the option `Default Language for new users`
1. Update
1. Try again the sequence you reported

**Comment by h-ohta** [comment] 2019-01-11 06:11
@yuki-takei 

I found that the option `Default Language for new users` is not set as shown in the following image.

![2019-01-11 13 34 29](https://user-images.githubusercontent.com/9547070/51015832-02b01680-15b1-11e9-9f08-1e0360a0976a.png)

Once I set that option as `Japanese`, press `Update` and  try again to login by google oauth, login succeeded.

Nomally, is that option set as either `Japanese` or `English`?

**Comment by yuki-takei** [comment] 2019-01-27 15:21
@h-ohta 
> Nomally, is that option set as either Japanese or English?

It should be set to English when you install GROWI ***cleanly***.
Although the sympton you reported might be caused when upgrading, I can't reproduce that at the moment.

Anyway, I think [the workaround I wrote](https://github.com/weseek/growi/issues/787#issuecomment-453099726) is effective, I'll close this issue for the time being. Thanks.

**Closed by yuki-takei** 2019-01-27 15:21 UTC
